"""
Fix Route
Applies AI-suggested fixes by creating branches and pull requests via PyGithub.
"""

from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional
from services.event_store import get_event_by_id, update_event
from services.github_service import create_fix_branch, update_file, create_pull_request

router = APIRouter()


class ApplyFixPayload(BaseModel):
    """Payload to apply a fix."""
    event_id: str
    file_to_change: Optional[str] = None
    change_content: Optional[str] = None


@router.post("/apply/fix")
async def apply_fix(payload: ApplyFixPayload):
    """
    Apply an AI-suggested fix by creating a branch, modifying the file, and opening a PR.
    Uses the stored diagnosis from the event, or overrides from the payload.
    """
    event = get_event_by_id(payload.event_id)
    if not event:
        return {"status": "error", "message": f"Event '{payload.event_id}' not found"}

    diagnosis = event.get("diagnosis")
    if not diagnosis:
        return {
            "status": "error",
            "message": "No AI diagnosis found for this event. Run /trigger/agent first.",
        }

    # Determine fix parameters
    file_to_change = payload.file_to_change or diagnosis.get("file_to_change", "")
    change_content = payload.change_content or diagnosis.get("change", "")
    issue_type = diagnosis.get("issue_type", "unknown")
    branch = event.get("branch", "main")

    # Create a fix branch
    fix_branch = f"launchloop/fix-{payload.event_id}"
    branch_result = create_fix_branch(fix_branch, base_branch=branch)

    if not branch_result.get("success"):
        return {
            "status": "error",
            "message": f"Failed to create branch: {branch_result.get('message')}",
        }

    # Update the file
    file_result = update_file(
        branch=fix_branch,
        file_path=file_to_change,
        new_content=change_content,
        commit_message=f"fix: {issue_type} — {diagnosis.get('explanation', 'AI-generated fix')[:80]}",
    )

    # Create a pull request
    pr_body = f"""## 🤖 LaunchLoop AI Auto-Fix

**Event ID:** `{payload.event_id}`
**Issue Type:** {issue_type}
**Risk Level:** {diagnosis.get('risk', 'unknown')}
**File Changed:** `{file_to_change}`

### AI Diagnosis
{diagnosis.get('explanation', 'No explanation available.')}

### Change Applied
```
{change_content}
```

---
*This PR was automatically generated by LaunchLoop AI Agent.*
"""

    pr_result = create_pull_request(
        branch=fix_branch,
        title=f"🔧 [LaunchLoop] Auto-fix: {issue_type} in {file_to_change}",
        body=pr_body,
    )

    # Update event with PR info
    if pr_result.get("success"):
        update_event(payload.event_id, {
            "fix_pr": {
                "number": pr_result.get("pr_number"),
                "url": pr_result.get("pr_url"),
                "status": "open",
            }
        })

    return {
        "status": "applied",
        "event_id": payload.event_id,
        "branch": branch_result,
        "file_update": file_result,
        "pull_request": pr_result,
        "message": "Fix applied and PR created successfully",
    }
